site_name: hextol
site_description: Hexadecimal comparison utilities.
site_url: https://mlmecham.github.io/hextol
repo_url: https://github.com/MLMecham/hextol
repo_name: MLMecham/hextol

theme:
  name: material
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
    - content.code.copy
    - search.suggest
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  palette:
    - scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

watch:
  - src/hextol

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MLMecham
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/mitchell-mecham/

copyright: Copyright &copy; 2026 Mitchell Mecham
